### ISSUE TITLE
Add support for python-click<=7 & python-rsa<=4

### ISSUE THREAD

**Issue by Musikolo** [cshamrick/stsauth#12]
Hi @cshamrick / @phillipjf ,

I'm trying to upgrade my [stsauth](https://aur.archlinux.org/packages/stsauth/) package to version `0.2.4`. However, I have found that `stsauth` requires `python-click < 7` and `python-rsa < 4` which are no longer officially supported in Arch Linux. 

Both dependencies released a major version last month, and I wonder if it would possible to include support for them:
- `python-rsa` release history: https://pypi.org/project/rsa/#history
- `python-click` release history: https://pypi.org/project/click/#history

Thank you!

P.S: On a side note, I've noticed that version `0.2.0` shows as the latest version at https://github.com/cshamrick/stsauth/releases It's nothing really important, but I thought you might want to fix it.

**Comment by phillipjf** [comment]
The `python-rsa` dependency comes in from `awscli` [here](https://github.com/aws/aws-cli/blob/develop/requirements.txt#L12) which specifies `rsa>=3.1.2,<=3.5.0`.  
Looks like it will be possible to update to `click==7.0` though.

**Comment by phillipjf** [comment]
I've released `v0.2.5` with `click==7.0`.

**Comment by Musikolo** [comment]
@phillipjf , thanks for your prompt support! ;-)

**Comment by Musikolo** [comment]
BTW, `0.2.4` showing as latest version now:
- https://github.com/cshamrick/stsauth/releases

Nothing terrible thought... :-)

**Comment by phillipjf** [comment]
Forgot to mark`v0.2.5`  as released, should show up now.
