### ISSUE TITLE
PyPI not upgraded to distribution version 1.1.1

### ISSUE THREAD

**Issue by Musikolo** [cshamrick/stsauth#77]
**Describe the bug**
When building the new version `1.1.1`,  I get the following error:
```
ERROR: Ignored the following yanked versions: 0.7.0
ERROR: Could not find a version that satisfies the requirement stsauth==1.1.1 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.8.0, 0.9.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0)
ERROR: No matching distribution found for stsauth==1.1.1
```

Looking at PyPI, it looks like last distribution version is `1.1.0`: https://pypi.org/project/stsauth/

I hope that helps.

Thanks.

**Comment by phillipjf** [comment]
Working with @cshamrick to get the credentials fixed and publish to PyPi.
https://github.com/cshamrick/stsauth/actions/runs/10963955356
